# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/beyondx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),beyondx)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G977B,bdbd1a5a09975e78ca7a4a408dd2dbdeaa1b1c0c)
$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G977N,c9decc8bcf27583c049c06272a2415aef0fbfd80)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G977B,432c49fb7d88d788cbae5bdc0dccd0d63b4fa698)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G977N,c94f62e7d29e1e8febf6ed212ffdc9f295fde406)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G977B,549de1fd135cb15293a5b52027c009daf6ef634b)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G977N,82ea8462af9811dc8dfdd395876d11281b7d5236)
$(call add-radio-file-sha1-checked,radio/models,6e52b708d06b9525eef96a6522b48584e837ef75)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G977B,9e3483e2a0d00be30bfe2ae189990d70d95750f7)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G977N,5694589c34489df095c116473e98941e69e0a305)
$(call add-radio-file-sha1-checked,radio/modem_5g.bin_SM-G977B,e00aa64164b4880e2fc9af4e0529825d558af89c)
$(call add-radio-file-sha1-checked,radio/modem_5g.bin_SM-G977N,415fe0bd303c44af85c1279c3032aca004ac0580)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G977B,54601ba958793df1942b616f8adaae3d613731c4)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G977N,ec0bd533c6bf8366ac139923bf0d597695d4f076)
$(call add-radio-file-sha1-checked,radio/modem_debug_5g.bin_SM-G977B,c3066b99c45fe7a647e75b953dffb394485015c8)
$(call add-radio-file-sha1-checked,radio/modem_debug_5g.bin_SM-G977N,19be25a2f62c52a3158a773ef44cb5a2d0963ef9)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G977B,40082486e3bd3364d9452f2bfbce6bc80e069577)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G977N,2e9b18ec8c0ffcf6a47d939f7ff2263d318cd678)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G977B,b5e6d1dcaf0d6e6bd3b96ed7aba75f09eade676a)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G977N,6a29c09387555b6b82d8e410d4bdf7c94c175c1e)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G977B,8d2b5f6770059f36f951df8587b6799475835bc6)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G977N,0c6b4ca515d93e236c09b02f30afcdda8972fa90)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G977B,a32926012e4240d2d41e5a4892e1b0b326baf093)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G977N,c942b701f5e5fc6331d241380a60780a9df77e8b)
$(call add-radio-file-sha1-checked,radio/version_SM-G977B,0d8f1a658280743e2bd5d6ba3dbf2aba8f6654ca)
$(call add-radio-file-sha1-checked,radio/version_SM-G977N,9c060c51755838028fdb865a819041b206c88a46)

endif
